// ==== BEGIN: d:\work24\souffle-lsp-plugin\example\puzzle\puzzle.dl ====
//// Farmer-Wolf-Goat-Cabbage Puzzle
//// Adopted from DES

.type Node <: symbol

.decl safe  (node1:Node, node2:Node, node3:Node, node4:Node)
.output safe  ()
.decl state (node1:Node, node2:Node, node3:Node, node4:Node)
.output state ()
.decl opp   (node1:Node, node2:Node)
.output opp   ()

// Initial state
state("n","n","n","n").
// Farmer takes Wolf
state(X,X,U,V) :-
  safe(X,X,U,V),
  opp(X,X1),
  state(X1,X1,U,V).
// Farmer takes Goat
state(X,Y,X,V) :-
  safe(X,Y,X,V),
  opp(X,X1),
  state(X1,Y,X1,V).
// Farmer takes Cabbage
state(X,Y,U,X) :-
  safe(X,Y,U,X),
  opp(X,X1),
  state(X1,Y,U,X1).
// Farmer goes by himself
state(X,Y,U,V) :-
  safe(X,Y,U,V),
  opp(X,X1),
  state(X1,Y,U,V).

// Opposite shores (n/s)
opp("n","s").
opp("s","n").

// Farmer is with Goat

// TODO: This triggers segfault
// safe(X,Y,X,V) :- safe(X,_,X,_).

// Rewrite non-ground rule  'safe(X,Y,X,V)' to:
safe("n","s","n","s").
safe("n","n","n","n").
safe("n","s","n","n").
safe("n","n","n","s").
safe("s","s","s","s").
safe("s","n","s","n").
safe("s","s","s","n").
safe("s","n","s","s").

// Farmer is not with Goat
safe(X,X,X1,X) :- opp(X,X1).


// ==== END: d:\work24\souffle-lsp-plugin\example\puzzle\puzzle.dl ====

// ==== BEGIN: d:\work24\souffle-lsp-plugin\example\shortest_path\shortest_path.dl ====
// Souffle - A Datalog Compiler
// Copyright (c) 2016, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

// Find the shortest paths between all nodes, the slow way
.type Node <: symbol

.decl Edge(n:Node, m:Node, w:number)
.input Edge()

// Find all paths
.decl Length   (n:Node, m:Node, l:number)
Length(x,y,t)  :- t=l, Edge(x,y,l).
Length(x,y,t+l)  :- Edge(x,z,l), Length(z,y,t).

// Filter out the longest path
.decl ShortestPath(n:Node, m:Node, l:number)
.output ShortestPath()
ShortestPath(x, y, a) :- Length(x, y, _), a = min Z : Length(x, y, Z).

// ==== END: d:\work24\souffle-lsp-plugin\example\shortest_path\shortest_path.dl ====

// ==== BEGIN: d:\work24\souffle-lsp-plugin\example\weighted_distances\weighted_distances.dl ====
// Souffle - A Datalog Compiler
// Copyright (c) 2016, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

// Type Node
.type Node <: symbol

//
// Edges non circular
//

.decl Edge        (n:Node, m:Node, w:number)

Edge("0","1",3).
Edge("1","2",5).
Edge("2","3",1).
Edge("1","4",-6).
Edge("4","2",-1).

//
// Reachable
//

.decl Reachable   (n:Node, m:Node, i:number)
.output Reachable   ()

Reachable(x,y,r)  :- r=w, Edge(x,y,w).
Reachable(x,y,d+w)  :- Edge(x,z,w), Reachable(z,y,d).


.decl ShortestDuplicates(n:Node, m:Node, i:number)
.output ShortestDuplicates()

ShortestDuplicates(x,y,a) :- Reachable(x,y,a), Reachable(x,y,b), a<b.

// ==== END: d:\work24\souffle-lsp-plugin\example\weighted_distances\weighted_distances.dl ====

// ==== BEGIN: d:\work24\souffle-lsp-plugin\example\orbits\orbits.dl ====
// Orbits of cosmological objects
// Rafael Caballero-Rold\'an, 2007
// Adopted from DES

.type D <: symbol

.decl star    (x:D)
.output star    ()
.decl orbits  (x:D,y:D)
.output orbits  ()
.decl planet  (x:D)
.output planet  ()
.decl intermediate (x:D,y:D)
.output intermediate ()
.decl satellite (x:D,y:D)
.output satellite ()

star("sun").
orbits("earth", "sun").
orbits("moon", "earth").

orbits(X,Y) :-
  orbits(X,Z),
  orbits(Z,Y).

satellite(X,Y) :-
  orbits(X,Y),
  !intermediate(X,Y),
  !star(Y).

planet(X) :-
  orbits(X,Y),
  star(Y),
  !intermediate(X,Y).

intermediate(X,Y) :-
  orbits(X,Z),
  orbits(Z,Y).



// ==== END: d:\work24\souffle-lsp-plugin\example\orbits\orbits.dl ====

// ==== BEGIN: d:\work24\souffle-lsp-plugin\example\catalan\catalan.dl ====
// Souffle - A Datalog Compiler
// Copyright (c) 2016, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

// Generate the Catalan numbers

// Generated catalan numbers will never exceed lim(n).
.decl lim(n : number)
.input lim()

.decl naturals(n : number)
naturals(0).
naturals(n+1) :- naturals(n), n < s, lim(s).

// Binomial Coefficients
.decl choose(n : number, k : number, v : number)
choose(n, n, 1) :- naturals(n).
choose(n, (n - k), v) :- choose(n, k, v).
choose(n+1, k+1, v1 + v2) :- choose(n, k, v1), choose(n, k+1, v2).

.decl catalan(n : number, v: number)
.output catalan()
catalan(n, v) :- choose(2*n, n, c), naturals(v), v=c/(n+1).



// ==== END: d:\work24\souffle-lsp-plugin\example\catalan\catalan.dl ====

// ==== BEGIN: d:\work24\souffle-lsp-plugin\example\clique\clique.dl ====
// Souffle - A Datalog Compiler
// Copyright (c) 2016, Oracle and/or its affiliates. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

//// Test Case adopted from Ocaml datalog

.type Node <: symbol

.decl reachable   (node1:Node, node2:Node)
.output reachable   ()
.decl same_clique (node1:Node, node2:Node)
.output same_clique ()
.decl edge        (node1:Node, node2:Node)
.output edge        ()

reachable(X,Y)   :- edge(X,Y).
reachable(X,Y)   :- edge(X,Z), reachable(Z,Y).
same_clique(X,Y) :- reachable(X,Y), reachable(Y,X).

edge("0", "1").
edge("1", "2").
edge("2", "3").
edge("3", "4").
edge("4", "5").
edge("5", "0").
edge("5", "6").
edge("6", "7").
edge("7", "8").
edge("8", "9").
edge("9", "10").
edge("10", "7").

// ==== END: d:\work24\souffle-lsp-plugin\example\clique\clique.dl ====

// ==== BEGIN: d:\work24\souffle-lsp-plugin\example\andersen\andersen.dl ====
// Souffle - A Datalog Compiler
// Copyright (c) 2016, Oracle and/or its affiliates. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

// Andersen's points-to analysis

// Define the domain of variables
.type var <: symbol

// Take addresses of other variables, i.e., y = &x;
.decl AddressOf(y:var, x:var)
.input AddressOf()

// Assign Statements, i.e.,  y = x;
.decl Assign(y:var, x:var)
.input Assign()

// Load Statements, i.e., y = *x;
.decl Load(y:var, x:var)
.input Load()

// Store Statements, i.e., *y = x;
.decl Store(y:var, x:var)
.input Store()

// PointsTo Relation, i.e., whether y may point to x
.decl PointsTo(y:var, x:var)
.output PointsTo()

PointsTo(y, x) :-
 AddressOf(y, x).

PointsTo(y, x) :-
 Assign(y, z),
 PointsTo(z, x).

PointsTo(y, w) :-
 Load(y, x),
 PointsTo(x, z),
 PointsTo(z, w).

PointsTo(z, w) :-
 Store(y, x),
 PointsTo(y, z),
 PointsTo(x, w).

// ==== END: d:\work24\souffle-lsp-plugin\example\andersen\andersen.dl ====

// ==== BEGIN: d:\work24\souffle-lsp-plugin\example\movies\movies.dl ====
// Souffle - A Datalog Compiler
// Copyright (c) 2016, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt


.type Text <: symbol

.decl Movie(id:number,title:Text,rating:Text)
.decl MovieActors(movieid:number,actorsid:number)
.decl Actors(actorid:number,name:Text)

Movie(1,"Movie a","2.3/10").
Movie(2,"Movie b","9.3/10").
Movie(3,"Movie c","8.6/10").

MovieActors(1,1).
MovieActors(1,2).
MovieActors(1,3).
MovieActors(2,2).
MovieActors(2,3).
MovieActors(2,4).
MovieActors(3,1).
MovieActors(3,4).

Actors(1,"John Smith").
Actors(2,"Joe Bloggs").
Actors(3,"Francesca Allsworth").
Actors(4,"Julia Thebest").



.decl MovieActorsText(title:Text, actorname:Text)
.output MovieActorsText()

MovieActorsText(c,d) :- MovieActors(a,b), Movie(a,c,_), Actors(b,d).

.decl JoeBloggsMovies(title:Text)
.output JoeBloggsMovies()

JoeBloggsMovies(a) :- MovieActorsText(a, b), match("Joe Bloggs", b).

.decl ActorsRatings(name:Text, rating:Text)
.output ActorsRatings()

ActorsRatings(a,rating) :- MovieActorsText(movie,a), Movie(_,movie_b,rating), match(movie, movie_b).

// ==== END: d:\work24\souffle-lsp-plugin\example\movies\movies.dl ====

// ==== BEGIN: d:\work24\souffle-lsp-plugin\example\hmmer\hmmer.dl ====
//
// Preliminary Version of a points-to analysis for C
//

.type Var <: symbol
.type Obj <: symbol

.decl DirectFlow(v:Var,w:Var)
.input DirectFlow()
.decl Load(v:Var,w:Var)
.input Load()
.decl Store(v:Var,w:Var)
.input Store()
.decl ExtReturn(v:Var,w:Var)
.input ExtReturn()
.decl EscapePtr(v:Var)
.input EscapePtr()
.decl HeapAlloc(v:Var,o:Obj)
.input HeapAlloc()
.decl StackAlloc(v:Var,o:Obj)
.input StackAlloc()
.decl Function(v:Var,o:Obj)
.input Function()
.decl Global(v:Var,o:Obj)
.input Global()

.decl LptrVar (v:Var)
.decl IsPtr (v:Var,o:Obj)
.decl Memory(o1:Obj,o2:Obj)
.decl IsReachable(v:Var,o:Obj)
.decl CFormat(o:Obj)
.decl CPtrLoad(v1:Var,v2:Var)
.output CPtrLoad()
.decl CPtrStore(v1:Var,v2:Var)
.output CPtrStore()

LptrVar(v) :- StackAlloc(v,_).
LptrVar(v) :- HeapAlloc(v,_).
LptrVar(v) :- Load(_,v).
LptrVar(v) :- Store(_,v).
LptrVar(v) :- DirectFlow(v,w), LptrVar(w).
LptrVar(v) :- DirectFlow(w,v), LptrVar(w).


IsPtr(v,o) :- HeapAlloc(v,o).
IsPtr(v,o) :- StackAlloc(v,o).
IsPtr(dest,o) :- DirectFlow(src,dest), IsPtr(src,o).
IsPtr(dest,o) :- Load(dest, addr), IsPtr(addr, o1), Memory(o1,o).
IsPtr(v,o) :- ExtReturn(arg,v), IsReachable(arg,o).

IsPtr(v,o) :- Global(v, o).

Memory(o1,o2) :- Store(src,addr), IsPtr(src,o2), IsPtr(addr, o1).

IsReachable(v,o) :- IsPtr(v,o).
IsReachable(v,o) :- Memory(o1,o), IsReachable(v,o1).

CFormat(o) :- EscapePtr(v), IsReachable(v,o).


IsPtr(v,"ttt_obj") :- ExtReturn(_,v).

CFormat("ttt_obj") :- ExtReturn(_,_).
Memory("ttt_obj", "ttt_obj") :- ExtReturn(_,_).


CPtrLoad(dest, addr) :- Load(dest, addr), IsPtr(addr, o), CFormat(o), LptrVar(dest).
CPtrStore(src, addr) :- Store(src, addr), IsPtr(addr, o), CFormat(o), LptrVar(src).

CFormat(o) :- CPtrLoad(_,v), IsPtr(v,o).
CFormat(o) :- CPtrStore(_,v), IsPtr(v,o).

CFormat(o) :- Load(v,addr), IsPtr(addr,o), !LptrVar(v).
CFormat(o) :- Store(v,addr), IsPtr(addr,o), !LptrVar(v).



// ==== END: d:\work24\souffle-lsp-plugin\example\hmmer\hmmer.dl ====

// ==== BEGIN: d:\work24\souffle-lsp-plugin\example\recipes\recipes.dl ====
// Souffle - A Datalog Compiler
// Copyright (c) 2016, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

.type Text <: symbol

.decl food(name:Text, carbs:number, fat:number, protein:number, per:number, measure:Text)
.input food()

.decl recipe(index: number, name:Text, amount: number, measure: Text)
.input recipe()

.decl max_index(result:number)
.output max_index()

max_index(a) :-  a = max a : recipe(a,_,_,_) .

.decl totals(name:Text, amount:number, carbs:number, fat:number, protein:number, cal:number)
.output totals()

totals(name, amount, amount*a/per, amount*b/per, amount*c/per, ((4*amount*a/per)+(9*amount*b/per)+(4*amount*c/per))) :- recipe(_, name, amount, _), food(name, a,b,c,per,_).


.decl calories(result:number)
.output calories()

calories(result) :- result = sum a : totals(_,_,_,_,_,a).

// ==== END: d:\work24\souffle-lsp-plugin\example\recipes\recipes.dl ====

// ==== BEGIN: d:\work24\souffle-lsp-plugin\example\fractional_knapsack\fractional_knapsack.dl ====
// Souffle - A Datalog Compiler
// Copyright (c) 2021, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

.type Item=[x:float,y:float]
.type List=[head:Item,amount:float,rest:List]

.decl capacity(value:float)
.input capacity

.decl item(value:float, weight:float)
.input item

.decl item_ratio(ratio:float, value:float, weight:float)
item_ratio(value/weight, value, weight) :- item(value, weight).

.decl first(value:float, weight:float)

.decl last(value:float, weight:float)

.decl next(value1:float, weight1:float, value2:float, weight2:float)
.decl next_candidate(value1:float, weight1:float, value2:float, weight2:float)

// first item has no prev
first(value,weight) :- item(value,weight), !next(_,_,value,weight).

// last item has no next
last(value,weight) :- item(value,weight), !next(value,weight,_,_).

next_candidate(v1,w1,v2,w2) :- item_ratio(r1,v1,w1), w2 = min w : { item_ratio(r,_,w), r = r1, w > w1 }, item_ratio(r1,v2,w2).

// next item in lexicographical ordering
next(v1,w1,v2,w2) :- item_ratio(r1,v1,w1),
		     r2 = min r : { item_ratio(r,_,_), r > r1 },
		     w2 = min w : { item_ratio(r,_,w), r = r2, w >= 0 },
	             item_ratio(r2,v2,w2), !next_candidate(v1,w1,_,_).

next(v1,w1,v2,w2) :- next_candidate(v1,w1,v2,w2).


.decl item_array(index:number, p:Item)
item_array(0,[v,w]) :- first(v,w).
item_array(i+1,[v2,w2]) :- item_array(i,[v1,w1]), next(v1,w1,v2,w2).


.decl knapsack_iteration(knapsack:List, index:number, weight:float, value:float)
knapsack_iteration(nil, count : item_array(_,_) - 1, cap, 0) :- capacity(cap).

// skip over iteration if we have exhausted capacity
knapsack_iteration(list, index-1, 0, value) :- knapsack_iteration(list, index, 0, value), index >= 0.

// otherwise exhaust the item and decrement
knapsack_iteration([[val,weight],amount,rest],index-1,remaining_cap, value+(val/weight)*amount) :-
	knapsack_iteration(rest, index, cap, value),
	item_array(index, [val,weight]),
	index >= 0,
	amount = min(cap,weight),
	remaining_cap = cap - amount,
	cap > 0.


.decl fractional_knapsack(val:float)
.output fractional_knapsack

fractional_knapsack(val) :- knapsack_iteration(_,-1,_,val).

// ==== END: d:\work24\souffle-lsp-plugin\example\fractional_knapsack\fractional_knapsack.dl ====

// ==== BEGIN: d:\work24\souffle-lsp-plugin\example\mmult\mmult.dl ====
// Souffle - A Datalog Compiler
// Copyright (c) 2017, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

.decl Mat1(row:number,column:number,value:number)

Mat1(1,1,2).
Mat1(1,2,4).
Mat1(2,1,3).
Mat1(2,2,5).

.output Mat1()


.decl Mat2(row:number,column:number, value:number)

Mat2(1,1,2).
Mat2(1,2,4).
Mat2(1,3,4).
Mat2(2,1,3).
Mat2(2,2,5).
Mat2(2,3,6).

.output Mat2()


.decl Product(i:number,j:number, k:number, value:number)

Product(i,j,k,value1*value2) :-
	Mat1(i,k,value1),Mat2(k,j,value2).


.decl Mat3(row:number,column:number, value:number)

Mat3(i,j, value) :-
	Mat1(i,_,_), Mat2(_,j,_), value = sum x : Product(i,j,_,x).

.output Mat3()


// ==== END: d:\work24\souffle-lsp-plugin\example\mmult\mmult.dl ====

